# Generated by Django 4.1.7 on 2023-03-01 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('dataset_file', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'ordering': ('-date',),
                'get_latest_by': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('mass', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('skin_color', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('homeworld', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starwars.datasetmetadata')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ('name',),
                'get_latest_by': ('name',),
            },
        ),
    ]
